name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v2

      - name: Set up Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: nightly

      - name: Build and Deploy
        run: |
          cargo build --release
          rm -rf ../dbs
          cd target/release
          ./similars-sled
