name: Similar CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: debian

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Rust
        run: curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh -s -- -y

      - name: Configure PATH environment variable
        run: echo "PATH=\"$HOME/.cargo/bin:$PATH\"" >> $GITHUB_ENV

      - name: Build and run
        run: cargo build --verbose && cargo run
